### ISSUE TITLE
This is an abuse of the issue system but...

### ISSUE THREAD

**Issue by bpunsky** [ReneHSZ/odin-openssl#1]
you should check out #odin on the Handmade Network Discord if you haven't, plenty of people who will give Odin advice/debugging help etc and may be willing to contribute to your libs!

https://discordapp.com/invite/awz66AN

**Comment by ReneHSZ** [comment]
Thank you, I will definitely check that out!

P.S.: It's fine to open issues as long as they are somehow helpful. I think this is very helpful, so it is not an abuse in my opinion. Thanks for great advice!

**Comment by ReneHSZ** [comment]
I'll close this now and when I have time to do so, I'll check it out!
